version: '3.7'

x-restart-policy: &restart_policy
  restart: unless-stopped


services:
#  db:
##    << : *restart_policy
#    build:
#      dockerfile: db_Dockerfile
#    env_file:
#      - .env
#    environment:
#      - POSTGRES_USER=${DB_USER}
#      - POSTGRES_PASSWORD=${DB_PASSWORD}
#      - POSTGRES_DB=${DB_NAME}
#      - POSTGRES_HOST_PORT=${DB_HOST_PORT}
#    ports:
#      - "${DB_HOST_PORT}:5432"
#    volumes:
#      - coffee_core:/var/lib/postgresql/data

  web:
#    << : *restart_policy
    container_name: project_coffee_web
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn projectCoffee.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
#      - media_volume:/usr/src/app/mediafiles
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - .env
#    depends_on:
#      - db

volumes:
#  media_volume:
#    driver: local
  static_volume:
    driver: local
  coffee_core_db_volume:
    driver: local